### PR TITLE
Add eslintrc and lint some files

### PR DESCRIPTION
**Pull request by axmmisaka**
I'm not 100% sure how the "design" (https://github.com/lf-lang/reactor-ts/issues/86) here is supposed to work, but I tried to run eslint and it looks really bad (lots of `unused-var` and `eqeqeq` issue); most of them are, sadly, not auto-fixable.

I fixed some, but not sure what route do we plan to proceed... Posting a draft PR here first

Speaking of which, we should also run `prettier` or similar things

### CODE REVIEW

**Comment by lhstrh** [comment]
We have #83 but have been reluctant to merge it because of outstanding PRs that would end up with conflicts...

**Comment by lhstrh** [comment]
The reason why CI fails is that it expects `lint-wish-eslint` to be a branch on `lf-lang/reactor-ts`. We can either try to fix this, or you can create a branch in this repo instead. If you don't have permission to do this I can grant it to you.

**Comment by lhstrh** [comment]
This patch might do the trick: https://github.com/lf-lang/reactor-ts/commit/91fd3b38dadb9293a77fc9793909d45ffe8aafad

**Comment by axmmisaka** [comment]
Closing this, when #83 is merged open a new one based off of that.

**Pull request closed without merging**
