### PR TITLE
Retrieval of reactor-ts via git and not the local filesystem

### PR DESCRIPTION
**Pull request by byeonggiljun**

### CODE REVIEW

**Comment by lhstrh** [comment]
Looks like a good solution to me!

**Comment by lhstrh** [comment]
That makes me wonder though; how does this work in the `lingua-franca` repo? The same fix wouldn't work there.

**Comment by lhstrh** [comment]
On `lingua-franca#master` we use the default `package.json` which currently points to `git://github.com/lf-lang/reactor-ts.git#master`. So we are testing against the correct runtime, it seems.

**Comment by byeonggiljun** [comment]
> On lingua-franca#master we use the default package.json which currently points to git://github.com/lf-lang/reactor-ts.git#master. So we are testing against the correct runtime, it seems.

I also think so. :)

**Review by lhstrh — APPROVED** [review]
:+1:

**Pull request merged**
