### PR TITLE
More `eslint` issues addressed

### LINKED ISSUE #162: Various `eslint`-suggested fixes
Yes and no - I made sure `eslint` won't complain, but some are simply suppressed by `eslint-disable-next-line` and added as TODO items.
Here are some examples:
- [x] `@typescript-eslint/no-this-alias` is suppressed entirely; it is addressed in #159 
- [x] Some Java style code that does not live well with ts, for example, empty abstract class and classes with only static methods
- [x] https://github.com/lf-lang/reactor-ts/blob/6db9fb0cf90be7c6acd75dbde2e2fcee8f961e61/src/core/port.ts#L90-L99 ; if this is changed the whole `reactor.ts` will explode
- [x] We have a lot of use of `any` and maybe there could be alternatives (mostly solved by #172 and #168)

Yet I think these changes will involve complex refactoring and should be addressed in individual issues

_Originally posted by @axmmisaka in https://github.com/lf-lang/reactor-ts/issues/160#issuecomment-1577684785_

### PR DESCRIPTION
**Pull request by lhstrh**
- [x] remove usages of `any`
- [x] rename `FOREVER()` and `NEVER()` (also in `lingua-franca`)
- [x] ~~`port.ts:90` and `port.ts:93`~~ see #184 
- [x] `reactor.ts:581` and `reactor.ts:1622`

Fixes  #162.

### CODE REVIEW

**Comment by lhstrh** [comment]
I'm not sure what to do about the failing bank test...

**Comment by lhstrh** [comment]
@hokeun (original author of the test), to reproduce, check out this branch and run `npm run test bank`.

**Comment by axmmisaka** [comment]
The error message is a bit confusing to me:

```
Argument of type '(member: MultiPeriodic) => OutMultiPort<number>' is not assignable to parameter of type '(reactor: MultiPeriodic) => Port<unknown> | MultiPort<unknown>'.
      Type 'OutMultiPort<number>' is not assignable to type 'Port<unknown> | MultiPort<unknown>'.
        Type 'OutMultiPort<number>' is not assignable to type 'MultiPort<unknown>'.
          The types returned by 'channels()' are incompatible between these types.
            Type 'OutPort<number>[]' is not assignable to type 'IOPort<unknown>[]'.
              Type 'OutPort<number>' is not assignable to type 'IOPort<unknown>'.
                The types of 'asWritable(...).getPort().getManager(...).addReceiver' are incompatible between these types.
                  Type '(port: WritablePort<number>) => void' is not assignable to type '(port: WritablePort<unknown>) => void'.
                    Types of parameters 'port' and 'port' are incompatible.
                      Type 'WritablePort<unknown>' is not assignable to type 'WritablePort<number>'.
                        The types returned by 'get()' are incompatible between these types.
                          Type 'unknown' is not assignable to type 'number | undefined'.
```
Notice that `Type '(port: WritablePort<number>) => void' is not assignable to type '(port: WritablePort<unknown>) => void'.` is because that `Type 'WritablePort<unknown>' is not assignable to type 'WritablePort<number>'.`, but we are assigning the other way around.

**Review by axmmisaka — APPROVED** [review]
👍🏼

**Pull request merged**
